services:
  qemu:
    container_name: qemu
    image: qemux/qemu-arm
    volumes:
      - ./boot.iso:/boot.iso
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m